// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// buyStock
void buyStock(std::string ticker, int quantity);
RcppExport SEXP FIX_buyStock(SEXP tickerSEXP, SEXP quantitySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type ticker(tickerSEXP);
    Rcpp::traits::input_parameter< int >::type quantity(quantitySEXP);
    buyStock(ticker, quantity);
    return R_NilValue;
END_RCPP
}
// sellStock
bool sellStock(std::string ticker, int quantity);
RcppExport SEXP FIX_sellStock(SEXP tickerSEXP, SEXP quantitySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type ticker(tickerSEXP);
    Rcpp::traits::input_parameter< int >::type quantity(quantitySEXP);
    __result = Rcpp::wrap(sellStock(ticker, quantity));
    return __result;
END_RCPP
}
// getPortfolio
bool getPortfolio();
RcppExport SEXP FIX_getPortfolio() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(getPortfolio());
    return __result;
END_RCPP
}
