# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

buyStock <- function(ticker, quantity) {
    invisible(.Call('FIX_buyStock', PACKAGE = 'FIX', ticker, quantity))
}

sellStock <- function(ticker, quantity) {
    .Call('FIX_sellStock', PACKAGE = 'FIX', ticker, quantity)
}

getPortfolio <- function() {
    .Call('FIX_getPortfolio', PACKAGE = 'FIX')
}

