# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initFIX <- function(settings) {
    invisible(.Call('pairFIX_initFIX', PACKAGE = 'pairFIX', settings))
}

buyStock <- function(ticker, price, quantity) {
    invisible(.Call('pairFIX_buyStock', PACKAGE = 'pairFIX', ticker, price, quantity))
}

sellStock <- function(ticker, price, quantity) {
    invisible(.Call('pairFIX_sellStock', PACKAGE = 'pairFIX', ticker, price, quantity))
}

getPortfolio <- function() {
    .Call('pairFIX_getPortfolio', PACKAGE = 'pairFIX')
}

